"""student_journey_checklist

Revision ID: 10ad76f2b0cd
Revises: 55ff41bac6dd
Create Date: 2026-08-12 10:51:55.504243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "10ad76f2b0cd"
down_revision: Union[str, Sequence[str], None] = "55ff41bac6dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_template_items",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stage", sa.String(length=60), nullable=True),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("depends_on_key", sa.String(length=50), nullable=True),
        sa.Column("due_after_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_template_items")),
        sa.UniqueConstraint("key", name=op.f("uq_checklist_template_items_key")),
    )
    op.create_table(
        "student_checklist_items",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("template_item_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stage", sa.String(length=60), nullable=True),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("depends_on_key", sa.String(length=50), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_custom", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_checklist_items_student_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["template_item_id"],
            ["checklist_template_items.id"],
            name=op.f("fk_student_checklist_items_template_item_id_checklist_template_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_checklist_items")),
        sa.UniqueConstraint("student_id", "key", name="uq_student_checklist_items_student_id_key"),
    )
    op.create_index("idx_student_checklist_items_student_id", "student_checklist_items", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_student_checklist_items_student_id", table_name="student_checklist_items")
    op.drop_table("student_checklist_items")
    op.drop_table("checklist_template_items")
    # ### end Alembic commands ###
