"""0002 ignition_catalog — Phase 4 catalog enrichment

Revision ID: 36b0c914200b
Revises: f7f30062eb35
Create Date: 2026-08-11 17:32:55.972756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "36b0c914200b"
down_revision: Union[str, Sequence[str], None] = "f7f30062eb35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_posts",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("author", sa.String(length=150), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_posts")),
        sa.UniqueConstraint("slug", name=op.f("uq_blog_posts_slug")),
    )
    op.create_index("idx_blog_posts_is_published", "blog_posts", ["is_published"], unique=False)
    op.create_index("idx_blog_posts_published_at", "blog_posts", ["published_at"], unique=False)
    op.create_table(
        "country_guides",
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("about", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hero_image_url", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.id"], name=op.f("fk_country_guides_country_id_countries"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_guides")),
        sa.UniqueConstraint("country_id", name=op.f("uq_country_guides_country_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_country_guides_slug")),
    )
    op.create_index("idx_country_guides_is_published", "country_guides", ["is_published"], unique=False)
    op.add_column("countries", sa.Column("average_tuition_usd", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column("countries", sa.Column("average_living_cost_usd", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column("countries", sa.Column("visa_information", sa.Text(), nullable=True))
    op.add_column("countries", sa.Column("display_order", sa.Integer(), server_default="0", nullable=False))
    op.add_column("programs", sa.Column("intakes_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("programs", sa.Column("highlights", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("programs", sa.Column("outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("programs", sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("programs", sa.Column("key_dates", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("programs", sa.Column("course_type", sa.String(length=50), nullable=True))
    op.add_column("programs", sa.Column("image_url", sa.Text(), nullable=True))
    op.add_column("universities", sa.Column("acceptance_rate", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("universities", sa.Column("faculties", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("highlights", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("campus_type", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("universities", "campus_type")
    op.drop_column("universities", "highlights")
    op.drop_column("universities", "faculties")
    op.drop_column("universities", "acceptance_rate")
    op.drop_column("programs", "image_url")
    op.drop_column("programs", "course_type")
    op.drop_column("programs", "key_dates")
    op.drop_column("programs", "requirements")
    op.drop_column("programs", "outcomes")
    op.drop_column("programs", "highlights")
    op.drop_column("programs", "intakes_summary")
    op.drop_column("countries", "display_order")
    op.drop_column("countries", "visa_information")
    op.drop_column("countries", "average_living_cost_usd")
    op.drop_column("countries", "average_tuition_usd")
    op.drop_index("idx_country_guides_is_published", table_name="country_guides")
    op.drop_table("country_guides")
    op.drop_index("idx_blog_posts_published_at", table_name="blog_posts")
    op.drop_index("idx_blog_posts_is_published", table_name="blog_posts")
    op.drop_table("blog_posts")
    # ### end Alembic commands ###
