"""finance

Revision ID: 3b4a406e84d6
Revises: 4be104956cdf
Create Date: 2026-08-12 11:25:03.732557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "3b4a406e84d6"
down_revision: Union[str, Sequence[str], None] = "4be104956cdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_rates",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=True),
        sa.Column("per_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("change_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("trend", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at_source", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency_rates")),
        sa.UniqueConstraint("code", name=op.f("uq_currency_rates_code")),
    )
    op.create_table(
        "country_cost_of_living",
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("proof_of_funds_name", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tuition_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("living_cost_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("insurance_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("visa_fee_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("biometrics_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_country_cost_of_living_country_id_countries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_cost_of_living")),
        sa.UniqueConstraint("country_id", name=op.f("uq_country_cost_of_living_country_id")),
    )
    op.create_table(
        "student_budgets",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("planned_monthly_income", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_budgets_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_budgets")),
        sa.UniqueConstraint("student_id", name=op.f("uq_student_budgets_student_id")),
    )
    op.create_table(
        "student_loans",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=True),
        sa.Column("approved_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("disbursed_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "approved",
                "partially_disbursed",
                "fully_disbursed",
                "rejected",
                name="loan_processing_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("sanctioned_at", sa.Date(), nullable=True),
        sa.Column("expected_full_disbursement", sa.Date(), nullable=True),
        sa.Column("repayment_starts_at", sa.Date(), nullable=True),
        sa.Column("tenure_months", sa.Integer(), nullable=True),
        sa.Column("monthly_repayment", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("collateral", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_loans_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_loans")),
        sa.UniqueConstraint("student_id", name=op.f("uq_student_loans_student_id")),
    )
    op.create_table(
        "student_savings_goals",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("savings", "emergency_fund", name="savings_goal_kind"), nullable=False),
        sa.Column("current_savings", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("monthly_contribution", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("recommended_months", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_savings_goals_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_savings_goals")),
        sa.UniqueConstraint("student_id", "kind", name="uq_student_savings_goals_student_id_kind"),
    )
    op.create_index("idx_student_savings_goals_student_id", "student_savings_goals", ["student_id"], unique=False)
    op.create_table(
        "budget_categories",
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("essential", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["student_budgets.id"],
            name=op.f("fk_budget_categories_budget_id_student_budgets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_categories")),
    )
    op.create_index("idx_budget_categories_budget_id", "budget_categories", ["budget_id"], unique=False)
    op.create_table(
        "cost_of_living_categories",
        sa.Column("cost_of_living_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("essential", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("phase", sa.String(length=30), nullable=True),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_of_living_id"],
            ["country_cost_of_living.id"],
            name=op.f("fk_cost_of_living_categories_cost_of_living_id_country_cost_of_living"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_of_living_categories")),
    )
    op.create_index(
        "idx_cost_of_living_categories_cost_of_living_id",
        "cost_of_living_categories",
        ["cost_of_living_id"],
        unique=False,
    )
    op.create_table(
        "loan_disbursements",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("disbursement_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "released", name="loan_disbursement_status"),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["student_loans.id"],
            name=op.f("fk_loan_disbursements_loan_id_student_loans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_disbursements")),
    )
    op.create_index("idx_loan_disbursements_loan_id", "loan_disbursements", ["loan_id"], unique=False)
    op.create_table(
        "loan_documents",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "uploaded", "verified", name="loan_document_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"], ["student_loans.id"], name=op.f("fk_loan_documents_loan_id_student_loans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_documents")),
    )
    op.create_index("idx_loan_documents_loan_id", "loan_documents", ["loan_id"], unique=False)
    op.create_table(
        "student_funding_sources",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "available", name="funding_source_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "verification",
            sa.Enum("unverified", "pending", "verified", name="funding_verification_status"),
            server_default="unverified",
            nullable=False,
        ),
        sa.Column("proof_document_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["proof_document_id"],
            ["documents.id"],
            name=op.f("fk_student_funding_sources_proof_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_funding_sources_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_funding_sources")),
    )
    op.create_index("idx_student_funding_sources_student_id", "student_funding_sources", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_student_funding_sources_student_id", table_name="student_funding_sources")
    op.drop_table("student_funding_sources")
    op.drop_index("idx_loan_documents_loan_id", table_name="loan_documents")
    op.drop_table("loan_documents")
    op.drop_index("idx_loan_disbursements_loan_id", table_name="loan_disbursements")
    op.drop_table("loan_disbursements")
    op.drop_index("idx_cost_of_living_categories_cost_of_living_id", table_name="cost_of_living_categories")
    op.drop_table("cost_of_living_categories")
    op.drop_index("idx_budget_categories_budget_id", table_name="budget_categories")
    op.drop_table("budget_categories")
    op.drop_index("idx_student_savings_goals_student_id", table_name="student_savings_goals")
    op.drop_table("student_savings_goals")
    op.drop_table("student_loans")
    op.drop_table("student_budgets")
    op.drop_table("country_cost_of_living")
    op.drop_table("currency_rates")
    # ### end Alembic commands ###
    # These enum types were created by the table DDL above; op.drop_table does
    # not drop them, so the next upgrade would hit DuplicateObject without
    # this. See app/db/types.py:enum_type.
    op.execute("DROP TYPE IF EXISTS funding_source_status")
    op.execute("DROP TYPE IF EXISTS funding_verification_status")
    op.execute("DROP TYPE IF EXISTS loan_processing_status")
    op.execute("DROP TYPE IF EXISTS loan_document_status")
    op.execute("DROP TYPE IF EXISTS loan_disbursement_status")
    op.execute("DROP TYPE IF EXISTS savings_goal_kind")
