"""lifecycle: apply intent, threads, milestones, notification metadata

Revision ID: 405db07a9f6f
Revises: f3c81ba4d072
Create Date: 2026-09-15 16:26:51.971852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "405db07a9f6f"
down_revision: Union[str, Sequence[str], None] = "f3c81ba4d072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Enum types this migration introduces.
#:
#: Three of them (`milestone_kind`, `thread_visibility`,
#: `message_attachment_kind`) are created for free: `op.create_table` emits
#: CREATE TYPE for any `sa.Enum` column it carries — see `app/db/types.py`.
#:
#: `offer_type` is not, because it arrives through `op.add_column`, which does
#: not. Hence the explicit create below. All four still have to be dropped by
#: hand in `downgrade`: `op.drop_table` leaves types behind, and a leftover
#: type makes the next upgrade fail with DuplicateObject.
NEW_ENUM_TYPES = ("milestone_kind", "thread_visibility", "message_attachment_kind", "offer_type")


def upgrade() -> None:
    # `op.add_column` with a `sa.Enum` does NOT emit CREATE TYPE on Postgres,
    # unlike `op.create_table`. Creating it up front rather than relying on
    # that asymmetry. IF NOT EXISTS so a partially-applied run is re-runnable.
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE offer_type AS ENUM ('conditional', 'unconditional', 'other'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apply_intents",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("university_id", sa.UUID(), nullable=True),
        sa.Column("intake_id", sa.UUID(), nullable=True),
        sa.Column("source_path", sa.String(length=300), nullable=True),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["claimed_by"], ["users.id"], name=op.f("fk_apply_intents_claimed_by_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["intake_id"], ["intakes.id"], name=op.f("fk_apply_intents_intake_id_intakes"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["programs.id"], name=op.f("fk_apply_intents_program_id_programs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_apply_intents_university_id_universities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apply_intents")),
    )
    op.create_index("idx_apply_intents_claimed_by", "apply_intents", ["claimed_by"], unique=False)
    op.create_index("idx_apply_intents_created_at", "apply_intents", ["created_at"], unique=False)
    op.create_index("idx_apply_intents_program_id", "apply_intents", ["program_id"], unique=False)
    op.create_table(
        "application_milestones",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("offer_received", "cas_received", "visa_approved", name="milestone_kind"), nullable=False
        ),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("seen_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_milestones_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_application_milestones_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_milestones")),
        sa.UniqueConstraint("application_id", "kind", name="uq_application_milestones_application_id_kind"),
    )
    op.create_index(
        "idx_application_milestones_student_unseen", "application_milestones", ["student_id", "seen_at"], unique=False
    )
    op.create_table(
        "message_threads",
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("shared", "internal", name="thread_visibility"),
            server_default="shared",
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("last_message_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_message_preview", sa.String(length=300), nullable=True),
        sa.Column("is_closed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_message_threads_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_message_threads_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_message_threads_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_message_threads_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_threads")),
    )
    op.create_index("idx_message_threads_application_id", "message_threads", ["application_id"], unique=False)
    op.create_index("idx_message_threads_last_message_at", "message_threads", ["last_message_at"], unique=False)
    op.create_index("idx_message_threads_lead_id", "message_threads", ["lead_id"], unique=False)
    op.create_index("idx_message_threads_student_id", "message_threads", ["student_id"], unique=False)
    op.create_table(
        "thread_messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("author_name", sa.String(length=200), nullable=True),
        sa.Column("is_from_student", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_thread_messages_author_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["message_threads.id"],
            name=op.f("fk_thread_messages_thread_id_message_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_messages")),
    )
    op.create_index("idx_thread_messages_author_id", "thread_messages", ["author_id"], unique=False)
    op.create_index("idx_thread_messages_thread_id", "thread_messages", ["thread_id", "created_at"], unique=False)
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("file", "image", "voice", name="message_attachment_kind"),
            server_default="file",
            nullable=False,
        ),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("stored_file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("duration_seconds", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["thread_messages.id"],
            name=op.f("fk_message_attachments_message_id_thread_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_attachments")),
    )
    op.create_index("idx_message_attachments_message_id", "message_attachments", ["message_id"], unique=False)
    op.add_column("applications", sa.Column("cas_received_date", sa.Date(), nullable=True))
    op.add_column("applications", sa.Column("cas_number", sa.String(length=50), nullable=True))
    op.add_column(
        "applications",
        sa.Column(
            "offer_type",
            postgresql.ENUM("conditional", "unconditional", "other", name="offer_type", create_type=False),
            nullable=True,
        ),
    )
    op.add_column("notifications", sa.Column("related_type", sa.String(length=40), nullable=True))
    op.add_column("notifications", sa.Column("related_id", sa.UUID(), nullable=True))
    op.add_column("notifications", sa.Column("action_url", sa.String(length=300), nullable=True))
    op.create_index("idx_notifications_related", "notifications", ["related_type", "related_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notifications_related", table_name="notifications")
    op.drop_column("notifications", "action_url")
    op.drop_column("notifications", "related_id")
    op.drop_column("notifications", "related_type")
    op.drop_column("applications", "offer_type")
    op.drop_column("applications", "cas_number")
    op.drop_column("applications", "cas_received_date")
    op.drop_index("idx_message_attachments_message_id", table_name="message_attachments")
    op.drop_table("message_attachments")
    op.drop_index("idx_thread_messages_thread_id", table_name="thread_messages")
    op.drop_index("idx_thread_messages_author_id", table_name="thread_messages")
    op.drop_table("thread_messages")
    op.drop_index("idx_message_threads_student_id", table_name="message_threads")
    op.drop_index("idx_message_threads_lead_id", table_name="message_threads")
    op.drop_index("idx_message_threads_last_message_at", table_name="message_threads")
    op.drop_index("idx_message_threads_application_id", table_name="message_threads")
    op.drop_table("message_threads")
    op.drop_index("idx_application_milestones_student_unseen", table_name="application_milestones")
    op.drop_table("application_milestones")
    op.drop_index("idx_apply_intents_program_id", table_name="apply_intents")
    op.drop_index("idx_apply_intents_created_at", table_name="apply_intents")
    op.drop_index("idx_apply_intents_claimed_by", table_name="apply_intents")
    op.drop_table("apply_intents")
    # ### end Alembic commands ###

    # Types outlive their tables and columns; drop them or the next
    # upgrade collides. Same rule as the initial schema's ENUM_TYPES.
    for enum_name in NEW_ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
