"""visa

Revision ID: 4be104956cdf
Revises: 903b04d865a8
Create Date: 2026-08-12 11:14:55.540640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "4be104956cdf"
down_revision: Union[str, Sequence[str], None] = "903b04d865a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visa_cases",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("destination_country", sa.String(length=100), nullable=False),
        sa.Column("visa_type", sa.String(length=150), nullable=False),
        sa.Column("application_number", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("preparing", "lodged", "approved", "refused", name="visa_case_status"),
            server_default="preparing",
            nullable=False,
        ),
        sa.Column("target_lodgement_date", sa.Date(), nullable=True),
        sa.Column("programme_start", sa.Date(), nullable=True),
        sa.Column("processing_estimate_weeks", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_visa_cases_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_visa_cases_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visa_cases")),
        sa.UniqueConstraint("application_id", name=op.f("uq_visa_cases_application_id")),
    )
    op.create_index("idx_visa_cases_student_id", "visa_cases", ["student_id"], unique=False)
    op.create_table(
        "departure_checklist_items",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["visa_cases.id"],
            name=op.f("fk_departure_checklist_items_case_id_visa_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departure_checklist_items")),
    )
    op.create_index("idx_departure_checklist_items_case_id", "departure_checklist_items", ["case_id"], unique=False)
    op.create_table(
        "visa_appointments",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("scheduled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("not_booked", "booked", "completed", "cancelled", name="visa_appointment_status"),
            server_default="not_booked",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["visa_cases.id"], name=op.f("fk_visa_appointments_case_id_visa_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visa_appointments")),
    )
    op.create_index("idx_visa_appointments_case_id", "visa_appointments", ["case_id"], unique=False)
    op.create_table(
        "visa_document_requirements",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("missing", "pending", "verified", "rejected", name="visa_document_requirement_status"),
            server_default="missing",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["visa_cases.id"],
            name=op.f("fk_visa_document_requirements_case_id_visa_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visa_document_requirements")),
    )
    op.create_index("idx_visa_document_requirements_case_id", "visa_document_requirements", ["case_id"], unique=False)
    op.create_table(
        "visa_fees",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paid", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("paid_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["visa_cases.id"], name=op.f("fk_visa_fees_case_id_visa_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visa_fees")),
    )
    op.create_index("idx_visa_fees_case_id", "visa_fees", ["case_id"], unique=False)
    op.create_table(
        "visa_stages",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("completed", "current", "upcoming", name="visa_stage_state"),
            server_default="upcoming",
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["visa_cases.id"], name=op.f("fk_visa_stages_case_id_visa_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visa_stages")),
    )
    op.create_index("idx_visa_stages_case_id", "visa_stages", ["case_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_visa_stages_case_id", table_name="visa_stages")
    op.drop_table("visa_stages")
    op.drop_index("idx_visa_fees_case_id", table_name="visa_fees")
    op.drop_table("visa_fees")
    op.drop_index("idx_visa_document_requirements_case_id", table_name="visa_document_requirements")
    op.drop_table("visa_document_requirements")
    op.drop_index("idx_visa_appointments_case_id", table_name="visa_appointments")
    op.drop_table("visa_appointments")
    op.drop_index("idx_departure_checklist_items_case_id", table_name="departure_checklist_items")
    op.drop_table("departure_checklist_items")
    op.drop_index("idx_visa_cases_student_id", table_name="visa_cases")
    op.drop_table("visa_cases")
    # These enum types were created by the table DDL above; op.drop_table does
    # not drop them, so the next upgrade would hit DuplicateObject without
    # this. See app/db/types.py:enum_type.
    op.execute("DROP TYPE IF EXISTS visa_case_status")
    op.execute("DROP TYPE IF EXISTS visa_stage_state")
    op.execute("DROP TYPE IF EXISTS visa_appointment_status")
    op.execute("DROP TYPE IF EXISTS visa_document_requirement_status")
    # ### end Alembic commands ###
