"""student_progress_and_points

Revision ID: 55ff41bac6dd
Revises: c447cbe03891
Create Date: 2026-08-11 18:31:13.245964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "55ff41bac6dd"
down_revision: Union[str, Sequence[str], None] = "c447cbe03891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points_rules",
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("points", sa.Integer(), server_default="0", nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("once_per_student", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_points_rules")),
        sa.UniqueConstraint("action", name=op.f("uq_points_rules_action")),
    )
    op.create_table(
        "progress_milestones",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Integer(), server_default="10", nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_milestones")),
        sa.UniqueConstraint("key", name=op.f("uq_progress_milestones_key")),
    )
    op.create_table(
        "student_milestones",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("milestone_id", sa.UUID(), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["progress_milestones.id"],
            name=op.f("fk_student_milestones_milestone_id_progress_milestones"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_milestones_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_milestones")),
        sa.UniqueConstraint("student_id", "milestone_id", name="uq_student_milestones_student_id_milestone_id"),
    )
    op.create_index("idx_student_milestones_student_id", "student_milestones", ["student_id"], unique=False)
    op.create_table(
        "student_points_ledger",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["points_rules.id"],
            name=op.f("fk_student_points_ledger_rule_id_points_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_points_ledger_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_points_ledger")),
        sa.UniqueConstraint(
            "student_id", "action", "reference_id", name="uq_student_points_ledger_student_action_reference"
        ),
    )
    op.create_index("idx_student_points_ledger_action", "student_points_ledger", ["action"], unique=False)
    op.create_index("idx_student_points_ledger_student_id", "student_points_ledger", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_student_points_ledger_student_id", table_name="student_points_ledger")
    op.drop_index("idx_student_points_ledger_action", table_name="student_points_ledger")
    op.drop_table("student_points_ledger")
    op.drop_index("idx_student_milestones_student_id", table_name="student_milestones")
    op.drop_table("student_milestones")
    op.drop_table("progress_milestones")
    op.drop_table("points_rules")
    # ### end Alembic commands ###
