"""support messages

Revision ID: 5d74cea62108
Revises: cbde73ef15a3
Create Date: 2026-08-12 16:26:07.715934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "5d74cea62108"
down_revision: Union[str, Sequence[str], None] = "cbde73ef15a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("is_from_student", sa.Boolean(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("fk_messages_sender_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_messages_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index("idx_messages_student_id", "messages", ["student_id"], unique=False)
    op.create_index(
        "idx_messages_student_unread",
        "messages",
        ["student_id", "is_read"],
        unique=False,
        postgresql_where=sa.text("is_read = FALSE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_student_unread", table_name="messages", postgresql_where=sa.text("is_read = FALSE"))
    op.drop_index("idx_messages_student_id", table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
