"""catalogue and cms

Revision ID: 7abd0d8c9a29
Revises: a1c7e93b52d4
Create Date: 2026-08-30 22:36:35.159605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "7abd0d8c9a29"
down_revision: Union[str, Sequence[str], None] = "a1c7e93b52d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Every Postgres ENUM this migration introduces.
#:
#: Table DDL emits `CREATE TYPE` for you (see `app/db/types.py`), so the five
#: enums below that appear on a *new* table are created by `op.create_table`.
#: `uk_region` is the exception: it only ever appears as a column added to the
#: existing `universities` table, and `op.add_column` does not create the type.
#: Hence the explicit create — without it the upgrade fails with
#: `type "uk_region" does not exist`.
#:
#: `op.drop_table` drops none of them, so every one is dropped by hand in
#: `downgrade()`. Skipping that leaves the types behind and the next upgrade
#: fails with `DuplicateObject`.
ENUM_TYPES: tuple[str, ...] = (
    "content_block_type",
    "content_kind",
    "course_level",
    "course_subject",
    "entry_route",
    "uk_region",
)

UK_REGION = postgresql.ENUM(
    "England — North",
    "England — Midlands",
    "England — South",
    "Scotland",
    "Wales",
    "Northern Ireland",
    name="uk_region",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    UK_REGION.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "course_profiles",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("qualification", sa.String(length=60), nullable=True),
        sa.Column(
            "subject",
            sa.Enum(
                "Computing",
                "Engineering",
                "Health",
                "Sciences",
                "Business",
                "Law",
                "Arts & Design",
                "Social Sciences",
                "Education",
                "Humanities",
                name="course_subject",
            ),
            nullable=True,
        ),
        sa.Column(
            "course_level",
            sa.Enum("Foundation", "Undergraduate", "Top-Up", "Integrated Masters", "Postgraduate", name="course_level"),
            nullable=True,
        ),
        sa.Column("duration_years", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("placement", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("what_you_study", sa.Text(), nullable=True),
        sa.Column("modules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("entry", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("career_outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_careers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_example", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_profiles")),
        sa.UniqueConstraint("slug", name=op.f("uq_course_profiles_slug")),
    )
    op.create_index("idx_course_profiles_is_published", "course_profiles", ["is_published"], unique=False)
    op.create_index("idx_course_profiles_slug", "course_profiles", ["slug"], unique=False)
    op.create_index("idx_course_profiles_subject", "course_profiles", ["subject"], unique=False)
    op.create_table(
        "content_pages",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.Enum("page", "guide", "post", "fragment", name="content_kind"), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("tag", sa.String(length=60), nullable=True),
        sa.Column("hero", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("seo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reading_minutes", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_content_pages_author_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_pages")),
        sa.UniqueConstraint("key", name=op.f("uq_content_pages_key")),
    )
    op.create_index("idx_content_pages_is_published", "content_pages", ["is_published"], unique=False)
    op.create_index("idx_content_pages_key", "content_pages", ["key"], unique=False)
    op.create_index("idx_content_pages_kind", "content_pages", ["kind"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("public_id", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=300), nullable=True),
        sa.Column("caption", sa.String(length=300), nullable=True),
        sa.Column("folder", sa.String(length=120), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_media_assets_uploaded_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index("idx_media_assets_folder", "media_assets", ["folder"], unique=False)
    op.create_index("idx_media_assets_kind", "media_assets", ["kind"], unique=False)
    op.create_table(
        "content_blocks",
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column(
            "block_type",
            sa.Enum(
                "prose",
                "cards",
                "timeline",
                "checklist",
                "faq",
                "callout",
                "stats",
                "list",
                "cta",
                "component",
                name="content_block_type",
            ),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"], ["content_pages.id"], name=op.f("fk_content_blocks_page_id_content_pages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_blocks")),
    )
    op.create_index("idx_content_blocks_page_id", "content_blocks", ["page_id"], unique=False)
    op.create_table(
        "scholarships",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=True),
        sa.Column("university_id", sa.UUID(), nullable=True),
        sa.Column("levels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("subjects", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nationality_group", sa.String(length=60), nullable=True),
        sa.Column("amount", sa.String(length=60), nullable=True),
        sa.Column("deadline", sa.String(length=60), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("apply_via", sa.Text(), nullable=True),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_example", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_scholarships_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scholarships")),
        sa.UniqueConstraint("slug", name=op.f("uq_scholarships_slug")),
    )
    op.create_index("idx_scholarships_is_published", "scholarships", ["is_published"], unique=False)
    op.create_index("idx_scholarships_slug", "scholarships", ["slug"], unique=False)
    op.create_index("idx_scholarships_university_id", "scholarships", ["university_id"], unique=False)
    op.create_table(
        "university_routes",
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column(
            "route_key",
            sa.Enum(
                "undergraduate",
                "international_year_one",
                "international_foundation_year",
                "pre_masters",
                "postgraduate",
                "top_up",
                "extended_masters",
                "mres",
                "dba",
                "nursing",
                name="entry_route",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("applicant_country_id", sa.UUID(), nullable=True),
        sa.Column("academic_criteria", sa.Text(), nullable=True),
        sa.Column("english_criteria", sa.Text(), nullable=True),
        sa.Column("english_waiver", sa.Text(), nullable=True),
        sa.Column("fee_structure", sa.Text(), nullable=True),
        sa.Column("scholarship_text", sa.Text(), nullable=True),
        sa.Column("gap_policy", sa.Text(), nullable=True),
        sa.Column("cas_deposit", sa.Text(), nullable=True),
        sa.Column("enrolment_fee", sa.Text(), nullable=True),
        sa.Column("deadlines", sa.Text(), nullable=True),
        sa.Column("previous_refusal", sa.Text(), nullable=True),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicant_country_id"],
            ["countries.id"],
            name=op.f("fk_university_routes_applicant_country_id_countries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_university_routes_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_university_routes")),
        # NULLS NOT DISTINCT: `applicant_country_id` is usually NULL, and
        # Postgres would otherwise treat every NULL as unique and let the same
        # (university, route) pair in twice — which would make the catalogue
        # importer non-idempotent. Requires PG 15+.
        sa.UniqueConstraint(
            "university_id",
            "route_key",
            "applicant_country_id",
            name="uq_university_routes_uni_route_country",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("idx_university_routes_is_published", "university_routes", ["is_published"], unique=False)
    op.create_index("idx_university_routes_university_id", "university_routes", ["university_id"], unique=False)
    op.add_column("programs", sa.Column("slug", sa.String(length=200), nullable=True))
    op.add_column("programs", sa.Column("course_profile_id", sa.UUID(), nullable=True))
    op.add_column("programs", sa.Column("route_id", sa.UUID(), nullable=True))
    op.add_column(
        "programs",
        sa.Column(
            "subject",
            sa.Enum(
                "Computing",
                "Engineering",
                "Health",
                "Sciences",
                "Business",
                "Law",
                "Arts & Design",
                "Social Sciences",
                "Education",
                "Humanities",
                name="course_subject",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "course_level",
            sa.Enum("Foundation", "Undergraduate", "Top-Up", "Integrated Masters", "Postgraduate", name="course_level"),
            nullable=True,
        ),
    )
    op.add_column("programs", sa.Column("qualification", sa.String(length=60), nullable=True))
    op.add_column("programs", sa.Column("campus", sa.String(length=120), nullable=True))
    op.add_column("programs", sa.Column("duration_years", sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column("programs", sa.Column("placement", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("programs", sa.Column("extra_requirements", sa.Text(), nullable=True))
    op.add_column("programs", sa.Column("fee_tier", sa.String(length=20), nullable=True))
    op.add_column("programs", sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("programs", sa.Column("is_example", sa.Boolean(), server_default="false", nullable=False))
    op.create_index("idx_programs_course_level", "programs", ["course_level"], unique=False)
    op.create_index("idx_programs_is_published", "programs", ["is_published"], unique=False)
    op.create_index("idx_programs_slug", "programs", ["slug"], unique=False)
    op.create_index("idx_programs_subject", "programs", ["subject"], unique=False)
    op.create_unique_constraint(op.f("uq_programs_slug"), "programs", ["slug"])
    op.create_foreign_key(
        op.f("fk_programs_route_id_university_routes"),
        "programs",
        "university_routes",
        ["route_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_programs_course_profile_id_course_profiles"),
        "programs",
        "course_profiles",
        ["course_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("universities", sa.Column("slug", sa.String(length=160), nullable=True))
    op.add_column(
        "universities",
        sa.Column(
            "region",
            sa.Enum(
                "England — North",
                "England — Midlands",
                "England — South",
                "Scotland",
                "Wales",
                "Northern Ireland",
                name="uk_region",
            ),
            nullable=True,
        ),
    )
    op.add_column("universities", sa.Column("tagline", sa.String(length=300), nullable=True))
    op.add_column("universities", sa.Column("overview", sa.Text(), nullable=True))
    op.add_column("universities", sa.Column("student_experience", sa.Text(), nullable=True))
    op.add_column("universities", sa.Column("careers_text", sa.Text(), nullable=True))
    op.add_column("universities", sa.Column("tuition_min", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("universities", sa.Column("tuition_max", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("universities", sa.Column("living_cost_monthly", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("universities", sa.Column("accommodation", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("entry", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("placement_year", sa.Boolean(), server_default="false", nullable=False))
    op.add_column(
        "universities", sa.Column("international_support", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("universities", sa.Column("facilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("subjects", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("monogram", sa.String(length=3), nullable=True))
    op.add_column("universities", sa.Column("founded", sa.String(length=20), nullable=True))
    op.add_column("universities", sa.Column("kind", sa.String(length=100), nullable=True))
    op.add_column("universities", sa.Column("campus", sa.String(length=200), nullable=True))
    op.add_column("universities", sa.Column("student_population", sa.String(length=50), nullable=True))
    op.add_column("universities", sa.Column("international_students", sa.String(length=120), nullable=True))
    op.add_column("universities", sa.Column("student_staff_ratio", sa.String(length=20), nullable=True))
    op.add_column("universities", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("milestones", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("rankings", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("awards", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("employability", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        "universities", sa.Column("interview_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("universities", sa.Column("imagery", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("universities", sa.Column("flyer_url", sa.Text(), nullable=True))
    op.add_column("universities", sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("universities", sa.Column("is_example", sa.Boolean(), server_default="false", nullable=False))
    op.create_index("idx_universities_is_published", "universities", ["is_published"], unique=False)
    op.create_index("idx_universities_slug", "universities", ["slug"], unique=False)
    op.create_unique_constraint(op.f("uq_universities_slug"), "universities", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_universities_slug"), "universities", type_="unique")
    op.drop_index("idx_universities_slug", table_name="universities")
    op.drop_index("idx_universities_is_published", table_name="universities")
    op.drop_column("universities", "is_example")
    op.drop_column("universities", "is_published")
    op.drop_column("universities", "flyer_url")
    op.drop_column("universities", "imagery")
    op.drop_column("universities", "interview_profile")
    op.drop_column("universities", "employability")
    op.drop_column("universities", "awards")
    op.drop_column("universities", "rankings")
    op.drop_column("universities", "milestones")
    op.drop_column("universities", "history")
    op.drop_column("universities", "student_staff_ratio")
    op.drop_column("universities", "international_students")
    op.drop_column("universities", "student_population")
    op.drop_column("universities", "campus")
    op.drop_column("universities", "kind")
    op.drop_column("universities", "founded")
    op.drop_column("universities", "monogram")
    op.drop_column("universities", "subjects")
    op.drop_column("universities", "facilities")
    op.drop_column("universities", "international_support")
    op.drop_column("universities", "placement_year")
    op.drop_column("universities", "entry")
    op.drop_column("universities", "accommodation")
    op.drop_column("universities", "living_cost_monthly")
    op.drop_column("universities", "tuition_max")
    op.drop_column("universities", "tuition_min")
    op.drop_column("universities", "careers_text")
    op.drop_column("universities", "student_experience")
    op.drop_column("universities", "overview")
    op.drop_column("universities", "tagline")
    op.drop_column("universities", "region")
    op.drop_column("universities", "slug")
    op.drop_constraint(op.f("fk_programs_course_profile_id_course_profiles"), "programs", type_="foreignkey")
    op.drop_constraint(op.f("fk_programs_route_id_university_routes"), "programs", type_="foreignkey")
    op.drop_constraint(op.f("uq_programs_slug"), "programs", type_="unique")
    op.drop_index("idx_programs_subject", table_name="programs")
    op.drop_index("idx_programs_slug", table_name="programs")
    op.drop_index("idx_programs_is_published", table_name="programs")
    op.drop_index("idx_programs_course_level", table_name="programs")
    op.drop_column("programs", "is_example")
    op.drop_column("programs", "is_published")
    op.drop_column("programs", "fee_tier")
    op.drop_column("programs", "extra_requirements")
    op.drop_column("programs", "placement")
    op.drop_column("programs", "duration_years")
    op.drop_column("programs", "campus")
    op.drop_column("programs", "qualification")
    op.drop_column("programs", "course_level")
    op.drop_column("programs", "subject")
    op.drop_column("programs", "route_id")
    op.drop_column("programs", "course_profile_id")
    op.drop_column("programs", "slug")
    op.drop_index("idx_university_routes_university_id", table_name="university_routes")
    op.drop_index("idx_university_routes_is_published", table_name="university_routes")
    op.drop_table("university_routes")
    op.drop_index("idx_scholarships_university_id", table_name="scholarships")
    op.drop_index("idx_scholarships_slug", table_name="scholarships")
    op.drop_index("idx_scholarships_is_published", table_name="scholarships")
    op.drop_table("scholarships")
    op.drop_index("idx_content_blocks_page_id", table_name="content_blocks")
    op.drop_table("content_blocks")
    op.drop_index("idx_media_assets_kind", table_name="media_assets")
    op.drop_index("idx_media_assets_folder", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("idx_content_pages_kind", table_name="content_pages")
    op.drop_index("idx_content_pages_key", table_name="content_pages")
    op.drop_index("idx_content_pages_is_published", table_name="content_pages")
    op.drop_table("content_pages")
    op.drop_index("idx_course_profiles_subject", table_name="course_profiles")
    op.drop_index("idx_course_profiles_slug", table_name="course_profiles")
    op.drop_index("idx_course_profiles_is_published", table_name="course_profiles")
    op.drop_table("course_profiles")

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
