"""student_profile_education_json

Revision ID: 8fd39f976eb4
Revises: cb3fe5ab944a
Create Date: 2026-08-12 11:59:34.155466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "8fd39f976eb4"
down_revision: Union[str, Sequence[str], None] = "cb3fe5ab944a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_profiles", sa.Column("education", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_profiles", "education")
    # ### end Alembic commands ###
