"""interviews

Revision ID: 903b04d865a8
Revises: 10ad76f2b0cd
Create Date: 2026-08-12 11:04:25.370495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "903b04d865a8"
down_revision: Union[str, Sequence[str], None] = "10ad76f2b0cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_feedback_bands",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("band", sa.String(length=50), nullable=False),
        sa.Column("tone", sa.String(length=30), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("improvements", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_feedback_bands")),
        sa.UniqueConstraint("key", name=op.f("uq_interview_feedback_bands_key")),
    )
    op.create_table(
        "interview_types",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), server_default="20", nullable=False),
        sa.Column("passing_score", sa.Integer(), server_default="70", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_types")),
        sa.UniqueConstraint("key", name=op.f("uq_interview_types_key")),
    )
    op.create_table(
        "interview_questions",
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("max_score", sa.Integer(), server_default="25", nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["interview_types.id"],
            name=op.f("fk_interview_questions_type_id_interview_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_questions")),
    )
    op.create_index("idx_interview_questions_type_id", "interview_questions", ["type_id"], unique=False)
    op.create_table(
        "interview_sessions",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", name="interview_session_status"),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("feedback_band_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["feedback_band_id"],
            ["interview_feedback_bands.id"],
            name=op.f("fk_interview_sessions_feedback_band_id_interview_feedback_bands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_interview_sessions_student_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["interview_types.id"],
            name=op.f("fk_interview_sessions_type_id_interview_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_sessions")),
    )
    op.create_index("idx_interview_sessions_student_id", "interview_sessions", ["student_id"], unique=False)
    op.create_table(
        "interview_answers",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("scorer_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["interview_questions.id"],
            name=op.f("fk_interview_answers_question_id_interview_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_interview_answers_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_answers")),
    )
    op.create_index("idx_interview_answers_session_id", "interview_answers", ["session_id"], unique=False)
    op.create_index(
        "uq_interview_answers_session_question", "interview_answers", ["session_id", "question_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_interview_answers_session_question", table_name="interview_answers")
    op.drop_index("idx_interview_answers_session_id", table_name="interview_answers")
    op.drop_table("interview_answers")
    op.drop_index("idx_interview_sessions_student_id", table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index("idx_interview_questions_type_id", table_name="interview_questions")
    op.drop_table("interview_questions")
    op.drop_table("interview_types")
    op.drop_table("interview_feedback_bands")
    # `interview_sessions.status` created this type via table DDL; op.drop_table
    # does not drop it, so the next upgrade would hit DuplicateObject without
    # this. See app/db/types.py:enum_type.
    op.execute("DROP TYPE IF EXISTS interview_session_status")
    # ### end Alembic commands ###
