"""eligibility assessments

Revision ID: b42df9339ebc
Revises: 7abd0d8c9a29
Create Date: 2026-08-31 13:41:24.522269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "b42df9339ebc"
down_revision: Union[str, Sequence[str], None] = "7abd0d8c9a29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_assessments",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("education", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("english", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("course", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("finance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("documents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("study_level", sa.String(length=50), nullable=True),
        sa.Column("preferred_course", sa.String(length=255), nullable=True),
        sa.Column("preferred_location", sa.String(length=100), nullable=True),
        sa.Column("preferred_universities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "academic_status",
            sa.Enum("likely_meets", "needs_review", "insufficient_information", name="eligibility_indicator"),
            nullable=False,
        ),
        sa.Column(
            "english_status",
            sa.Enum("likely_meets", "needs_review", "insufficient_information", name="eligibility_indicator"),
            nullable=False,
        ),
        sa.Column(
            "financial_status",
            sa.Enum("likely_meets", "needs_review", "insufficient_information", name="eligibility_indicator"),
            nullable=False,
        ),
        sa.Column(
            "document_status",
            sa.Enum("likely_meets", "needs_review", "insufficient_information", name="eligibility_indicator"),
            nullable=False,
        ),
        sa.Column(
            "overall_status",
            sa.Enum(
                "preliminary_likely_eligible",
                "needs_counsellor_review",
                "more_information_required",
                name="eligibility_overall",
            ),
            nullable=False,
        ),
        sa.Column("document_readiness", sa.Integer(), server_default="0", nullable=False),
        sa.Column("assessment_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assessment_version", sa.String(length=10), server_default="v1", nullable=False),
        sa.Column("source_page", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("consent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_eligibility_assessments_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_eligibility_assessments_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_assessments")),
    )
    op.create_index("idx_eligibility_assessments_lead_id", "eligibility_assessments", ["lead_id"], unique=False)
    op.create_index(
        "idx_eligibility_assessments_overall_status", "eligibility_assessments", ["overall_status"], unique=False
    )
    op.create_index(
        "idx_eligibility_assessments_submitted_at", "eligibility_assessments", ["submitted_at"], unique=False
    )
    op.create_index("idx_eligibility_assessments_user_id", "eligibility_assessments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_eligibility_assessments_user_id", table_name="eligibility_assessments")
    op.drop_index("idx_eligibility_assessments_submitted_at", table_name="eligibility_assessments")
    op.drop_index("idx_eligibility_assessments_overall_status", table_name="eligibility_assessments")
    op.drop_index("idx_eligibility_assessments_lead_id", table_name="eligibility_assessments")
    op.drop_table("eligibility_assessments")
    # ### end Alembic commands ###

    # `op.drop_table` does not drop the enum types its DDL created — see
    # `app/db/types.py`. Without this the next upgrade fails with
    # DuplicateObject, which is exactly what `upgrade head` -> `downgrade -1`
    # -> `upgrade head` is run to catch.
    for enum_name in ("eligibility_indicator", "eligibility_overall"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
