"""0003 student_portal_foundations — Phase 4

Revision ID: c447cbe03891
Revises: 36b0c914200b
Create Date: 2026-08-11 17:33:56.734676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "c447cbe03891"
down_revision: Union[str, Sequence[str], None] = "36b0c914200b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_saved_universities",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_student_saved_universities_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_student_saved_universities_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_saved_universities")),
        sa.UniqueConstraint(
            "student_id", "university_id", name="uq_student_saved_universities_student_id_university_id"
        ),
    )
    op.create_index(
        "idx_student_saved_universities_student_id", "student_saved_universities", ["student_id"], unique=False
    )
    op.create_table(
        "student_compare_courses",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_student_compare_courses_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_compare_courses_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_compare_courses")),
        sa.UniqueConstraint("student_id", "program_id", name="uq_student_compare_courses_student_id_program_id"),
    )
    op.create_index("idx_student_compare_courses_student_id", "student_compare_courses", ["student_id"], unique=False)
    op.create_table(
        "student_saved_courses",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_student_saved_courses_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_student_saved_courses_student_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_saved_courses")),
        sa.UniqueConstraint("student_id", "program_id", name="uq_student_saved_courses_student_id_program_id"),
    )
    op.create_index("idx_student_saved_courses_student_id", "student_saved_courses", ["student_id"], unique=False)
    op.add_column(
        "employee_profiles", sa.Column("specialities", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("employee_profiles", sa.Column("avatar_initials", sa.String(length=4), nullable=True))
    op.add_column(
        "student_profiles", sa.Column("onboarding_completed", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("student_profiles", sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("student_profiles", sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("student_profiles", sa.Column("test_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_profiles", "test_scores")
    op.drop_column("student_profiles", "preferences")
    op.drop_column("student_profiles", "address")
    op.drop_column("student_profiles", "onboarding_completed")
    op.drop_column("employee_profiles", "avatar_initials")
    op.drop_column("employee_profiles", "specialities")
    op.drop_index("idx_student_saved_courses_student_id", table_name="student_saved_courses")
    op.drop_table("student_saved_courses")
    op.drop_index("idx_student_compare_courses_student_id", table_name="student_compare_courses")
    op.drop_table("student_compare_courses")
    op.drop_index("idx_student_saved_universities_student_id", table_name="student_saved_universities")
    op.drop_table("student_saved_universities")
    # ### end Alembic commands ###
