"""dashboard_preferences

Revision ID: cb3fe5ab944a
Revises: 3b4a406e84d6
Create Date: 2026-08-12 11:39:31.443501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "cb3fe5ab944a"
down_revision: Union[str, Sequence[str], None] = "3b4a406e84d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_dashboard_settings",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("preferred_currency", sa.String(length=3), nullable=True),
        sa.Column("email_notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("push_notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("show_points_widget", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_student_dashboard_settings_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_dashboard_settings")),
        sa.UniqueConstraint("student_id", name=op.f("uq_student_dashboard_settings_student_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_dashboard_settings")
    # ### end Alembic commands ###
