"""student profile citizenship number

Revision ID: cbde73ef15a3
Revises: b987163a5ae1
Create Date: 2026-08-12 16:22:51.205152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "cbde73ef15a3"
down_revision: Union[str, Sequence[str], None] = "b987163a5ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_profiles", sa.Column("citizenship_number", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_profiles", "citizenship_number")
    # ### end Alembic commands ###
